import {Assistant} from "next/font/google";
import "./globals.css";
import { ToastContainer} from "react-toastify";
import GlobalProvider from "@/components/GlobalProvider/GlobalProvider";

const assistantFont = Assistant({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  display1: "swap",

})
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={assistantFont.className}>
        <GlobalProvider>
        <ToastContainer />
        {children}
        </GlobalProvider>
      </body>
    </html>
  );
}
